name: Daily Commit

on:
  schedule:
    - cron: '30 18 * * *'  # Runs at 18:30 UTC daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  create-daily-commit:
    runs-on: ubuntu-latest
    name: Create Daily Commit (23f3004024@ds.study.iitm.ac.in)
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Git config
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "23f3004024@ds.study.iitm.ac.in"
          
      - name: Create and commit daily update
        run: |
          echo "Daily update: $(date)" >> daily-updates.txt
          git add daily-updates.txt
          git commit -m "Add daily update for $(date)"
          git push
